# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1znvYvO7sIVgII9ndyJ2VuOI4I6PlCIoh
"""

import pandas as pd

# Define bill columns
bill_columns = ['S.no', 'Item', 'Quantity', 'Total Cost']

# Create an empty DataFrame to store bill details
bill_df = pd.DataFrame(columns=bill_columns)

# Shopping cart items with initial quantities and costs
shopping_cart = {
    'Biscuits': {'Quantity': 5, 'Cost/Item': 20.5},
    'Cereals': {'Quantity': 10, 'Cost/Item': 90.0},
    'Chicken': {'Quantity': 20, 'Cost/Item': 100.0}
}

count = 0

while True:
    user_input = int(input("What do you want to purchase? 1. Biscuits, 2. Cereals, 3. Chicken: "))
    if user_input in [1, 2, 3]:
        item = list(shopping_cart.keys())[user_input - 1]
        quantity = int(input(f"How many {item} packets do you want to purchase: "))
        if quantity <= shopping_cart[item]['Quantity']:
            # Update item quantity in shopping cart
            shopping_cart[item]['Quantity'] -= quantity
            total_cost = quantity * shopping_cart[item]['Cost/Item']
            count += 1
            # Add item to bill DataFrame
            new_row = {
                'S.no': len(bill_df) + 1,
                'Item': item,
                'Quantity': quantity,
                'Total Cost': total_cost
            }
            bill_df = pd.concat([bill_df, pd.DataFrame([new_row])], ignore_index=True)
            input3 = input("Do you want to continue shopping? (Y/N): ")
            if input3.upper() == 'N':
                if count > 0:
                    input4 = input("Enter your name: ")
                    input5 = input("Enter your address: ")
                    input6 = int(input("Enter the distance from the store (5/10/15/30): "))
                    if 0 < input6 <= 15:
                        dc = 50
                        print('Delivery charge: 50 Rs will be levied for distance between 0 to 15')
                    elif 15 < input6 <= 30:
                        dc = 100
                        print('Delivery charge: 100 Rs will be levied for distance between 0 to 15')
                    print("Generating Bill...\n")
                    print(bill_df)
                    print("Total items cost:", bill_df['Total Cost'].sum())
                    print("Total Bill Amount (including delivery charges):", bill_df['Total Cost'].sum() + dc)
                    print("Name:", input4)
                    print("Address:", input5)
                    print("Thank you for shopping with us!")
                    break
        else:
            print(f"Available quantity of {item} is {shopping_cart[item]['Quantity']}")
    else:
        print("Invalid item selected.")